from __future__ import annotations
from typing import Protocol, Optional
from models import User, Work, Review, SiteProfile, Like


class AuthService(Protocol):
    def login_url(self, provider: str, redirect_uri: str) -> str: ...
    def handle_callback(self, provider: str, request) -> User: ...
    def mock_login(self, provider: str, as_admin: bool = False) -> User: ...
    def providers_ready(self) -> dict[str, bool]: ...


class Store(Protocol):
    def get_profile(self) -> SiteProfile: ...
    def update_profile(self, data: dict) -> SiteProfile: ...

    def list_works(self, published_only: bool = True, category: str | None = None) -> list[Work]: ...
    def get_work(self, slug: str) -> Optional[Work]: ...
    def get_work_by_id(self, work_id: str) -> Optional[Work]: ...
    def upsert_work(self, work: Work) -> Work: ...
    def delete_work(self, work_id: str) -> None: ...
    def categories(self) -> list[str]: ...

    def upsert_user(self, user: User) -> User: ...
    def get_user(self, user_id: str) -> Optional[User]: ...
    def get_user_by_provider(self, provider: str, provider_id: str) -> Optional[User]: ...
    def list_users(self) -> list[User]: ...

    def toggle_like(self, work_id: str, user_id: str) -> tuple[bool, int]: ...
    def user_liked(self, work_id: str, user_id: str) -> bool: ...
    def like_count(self, work_id: str) -> int: ...

    def add_review(self, review: Review) -> Review: ...
    def list_reviews(self, work_id: str) -> list[Review]: ...
    def review_count(self, work_id: str) -> int: ...
    def user_reviewed(self, work_id: str, user_id: str) -> bool: ...
